apiVersion: v1
kind: ServiceAccount
metadata:
  name: pr-review-api
  namespace: repo-agent-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pr-review-api-role
  namespace: repo-agent-system
rules:
- apiGroups: ["custom.agents.x-k8s.io"]
  resources: ["reviewsandboxes", "issuesandboxes"]
  verbs: ["get", "list", "delete", "patch", "update"]
- apiGroups: ["review.gemini.google.com"]
  resources: ["repowatches"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pr-review-api-binding
  namespace: repo-agent-system
subjects:
- kind: ServiceAccount
  name: pr-review-api
roleRef:
  kind: Role
  name: pr-review-api-role
  apiGroup: rbac.authorization.k8s.io
