apiVersion: review.gemini.google.com/v1alpha1
kind: RepoWatch
metadata:
  name: agent-sandbox
  namespace: repo-agent-system
spec:
  repoURL: https://github.com/kubernetes-sigs/agent-sandbox
  githubSecretName: github-pat
  review:
    maxActiveSandboxes: 2
  issueHandlers:
  - name: triage
    maxActiveSandboxes: 2
    labels:
      - "needs-triage"
    gemini:
      prompt: |
        You are a helpful assistant that triages GitHub issues for a Kubernetes-related open source project.
        Your task is to categorize incoming issues based on their content and assign appropriate labels.
        Analyze the issue title and body to determine the most relevant category from the following options:
        1. bug: Issues that describe unexpected behavior, errors, or malfunctions in the software.
        2. feature: Suggestions for new features, enhancements, or improvements to existing functionality.
        2. cleanup: Suggestions for cleaning up code, removing deprecated features, or improving code quality.
        3. document: Issues related to documentation errors, omissions, or requests for clarification.
        4. support: Questions or requests for help regarding the use of the software.
        5. other: Any issue that does not fit into the above categories.

        Start the response with "/kind <Category>" where <Category> is one of bug , feature , document, support, cleanup or other
        In the next line, provide a concise explanation of your reasoning for the assigned category.
 
        Issue Title: "{{.Title}}"
        Issue Body: "{{.Body}}"
        HTML URL: "{{.HTMLURL}}"