apiVersion: "configdir.gke.io/v1alpha1"
kind: "ConfigDir"
metadata:
  name: "my-review-agent-config"
  namespace: "gemini-system"
spec:
  # The controller will use this selector to find all ConfigMap
  # objects associated with this project config.
  fileContentSelector:
    matchLabels:
      project: my-review-agent
  files:
    - path: "prompts/summarize.txt"
      source:
        inline: "Summarize the following code changes..."

    - path: "tools/linter-config.json"
      source:
        configMapRef:
          name: "linter-configs"
          key: "config.json"

    - path: "credentials/api-key.txt"
      source:
        secretRef:
          name: "gemini-api-keys"
          key: "review-agent-key"

    - path: "assets/logo.png"
      source:
        # The key 'logo.png' must exist in a ConfigMap
        # object matching the fileContentSelector above.
        fileContentKey: "logo.png"

    - path: "external/onboarding.md"
      source:
        url:
          location: "https://example.com/onboarding-docs/v1.md"
          sha256: "c3ab8ff13720e8ad9047dd39466b3c8974e592c2fa383d4a3960714caef0c4f2" # Optional, for integrity
          # Optional secret for auth headers (e.g., "Authorization: Bearer <token>")
          secretRef:
            name: "external-url-auth"
            key: "auth-header"
